// SRM Institute of Science and Technology (SRM IST), Kattankulathur (KTR) Main Campus Dataset
// Grounded in official SRM 360 Virtual Tour (https://webstor.srmist.edu.in/web_assets/srmist-virtual-tour-vo/)
// and SRMIST Faculty Directory (https://www.srmist.edu.in/faculty & /staff-finder/)

export const SRM_KTR_DATA = {
  campusInfo: {
    name: "SRM Institute of Science and Technology",
    campus: "Kattankulathur (KTR) Main Campus",
    location: "GST Road (NH 45), Potheri, Chengalpattu Dist, Tamil Nadu - 603203",
    shortName: "SRM IST KTR",
    tagline: "Official Campus Wayfinding & Staff Locator (Virtual Tour Grounded)"
  },

  // Major Campus Buildings & Zones identified in the Virtual Tour
  // Major Campus Buildings & Zones (Accurately grounded in Drone Aerial, Layout Plan, and Virtual Tour)
  buildings: [
    {
      id: "bldg-ub",
      name: "University Building (UB)",
      shortName: "University Building",
      code: "UB",
      zone: "UB Zone",
      road: "Swami Vivekananda Road",
      floorsCount: 15,
      x: 270,
      y: 310,
      width: 110,
      height: 95,
      floors: [
        { level: 0, name: "Ground Floor", code: "G", desc: "Main Reception, University Post Office, Indian Bank, Security Ops" },
        { level: 1, name: "1st Floor", code: "1F", desc: "Registrar's Office, Admissions Area, International Relations & Civil Eng Dept (UB-108)" },
        { level: 2, name: "2nd Floor", code: "2F", desc: "School of Mechanical Engineering Dean & Faculty Corridor (UB-201 to 230)" },
        { level: 3, name: "3rd Floor", code: "3F", desc: "Dean of Academics (UB-302), Controller of Examinations (COE) & VC Secretariat" },
        { level: 11, name: "11th Floor", code: "11F", desc: "Electronics & Communication Eng (ECE) Dept & Microelectronics Lab (UB-1101 to 1130)" },
        { level: 15, name: "15th Floor", code: "15F", desc: "Board Room (Dr. Venkatraman Ramakrishnan Hall), Leadership Suites, Dr. S. Radhakrishnan Hall" }
      ],
      description: "Iconic 15-story administrative landmark situated directly inside the Main Arch Gate on Swami Vivekananda Road. Houses Chancellor, VC, Registrar, Mechanical, Civil, and ECE departments.",
      category: "Administration & Engineering",
      photo: "assets/prof_senior.jpg"
    },
    {
      id: "bldg-lib",
      name: "SRM Central Library",
      shortName: "Central Library",
      code: "LIB",
      zone: "Learning Areas",
      road: "Swami Vivekananda Road",
      floorsCount: 4,
      x: 395,
      y: 315,
      width: 95,
      height: 80,
      floors: [
        { level: 0, name: "Ground Floor", code: "G", desc: "Circulation Desk, RFID Checkouts, Periodicals & Newspaper Section" },
        { level: 1, name: "1st Floor", code: "1F", desc: "Engineering & Technology Stacks, Digital IEEE/ACM E-Library" },
        { level: 2, name: "2nd Floor", code: "2F", desc: "Research Archive, Ph.D. Study Carrels & Quiet Study Hall" }
      ],
      description: "Air-conditioned 4-story learning resource center situated adjacent to University Building on Swami Vivekananda Road with over 150,000 volumes, RFID checkout kiosks, and digital research archives.",
      category: "Library & Study"
    },
    {
      id: "bldg-bel",
      name: "Basic Engineering Lab (BEL) Block",
      shortName: "BEL Block & Workshops",
      code: "BEL",
      zone: "BEL Zone",
      road: "Sir C.V. Raman Road",
      floorsCount: 4,
      x: 390,
      y: 215,
      width: 100,
      height: 70,
      floors: [
        { level: 0, name: "Ground Floor", code: "G", desc: "Machine Shops, Welding Lab, Sheet Metal Lab, Fitting Lab & Carpentry" },
        { level: 1, name: "1st Floor", code: "1F", desc: "Basic Electrical Labs (BEL-104), FAB Lab, Prototyping Labs 1 & 2" },
        { level: 2, name: "2nd Floor", code: "2F", desc: "Electrical and Electronics Engineering (EEE) Dept (BEL-201 to 225)" }
      ],
      description: "First-year engineering laboratory complex, machine shops, FAB Lab, and Department of Electrical & Electronics Engineering on Sir C.V. Raman Road.",
      category: "Laboratories & Workshops"
    },
    {
      id: "bldg-bio",
      name: "School of Bio-Engineering",
      shortName: "Bioengineering Block",
      code: "BIO",
      zone: "Bio Zone",
      road: "Mahakavi Bharathiyar Road",
      floorsCount: 6,
      x: 495,
      y: 125,
      width: 95,
      height: 65,
      floors: [
        { level: 0, name: "Ground Floor", code: "G", desc: "Biotechnology & Microbiology Labs, Plant Tissue Culture" },
        { level: 1, name: "1st Floor", code: "1F", desc: "School of Bioengineering Dean (BIO-101), Biomedical & Genetic Eng Cabins" },
        { level: 2, name: "2nd Floor", code: "2F", desc: "Genomics Research & Bioinformatics Computational Suite (BIO-202)" },
        { level: 3, name: "3rd Floor", code: "3F", desc: "Nanotechnology Labs & Dean Research Office (BIO-301)" }
      ],
      description: "Dedicated 6-story science complex on Mahakavi Bharathiyar Road for Biotechnology, Biomedical Engineering, Genetic Engineering, and Nanotechnology.",
      category: "Academic & Research"
    },
    {
      id: "bldg-tp",
      name: "Tech Park (TP)",
      shortName: "Tech Park Tower",
      code: "TP",
      zone: "Tech Park Zone",
      road: "Sir C.V. Raman Road",
      floorsCount: 15,
      x: 620,
      y: 165,
      width: 120,
      height: 105,
      floors: [
        { level: 0, name: "Ground Floor", code: "G", desc: "Main Lobby, Tech Park Food Court, ATM, Turnstiles" },
        { level: 1, name: "1st Floor", code: "1F", desc: "Ramanujan Seminar Hall, Basic Computing Labs" },
        { level: 6, name: "6th Floor", code: "6F", desc: "Computational Intelligence (CINTEL) Dept & Staff Cabins (TP-601 to 630)" },
        { level: 7, name: "7th Floor", code: "7F", desc: "Computing Technologies (CTECH) Dept & Faculty Suites (TP-701 to 735)" },
        { level: 8, name: "8th Floor", code: "8F", desc: "Turing Hall, School of Computing Chairperson Suite (TP-801) & Senior Cabins" },
        { level: 9, name: "9th Floor", code: "9F", desc: "Networking and Communications (NWC) Dept (TP-901 to 930) & Cisco Lab" },
        { level: 10, name: "10th Floor", code: "10F", desc: "Data Science & Business Systems (DSBS) Dept (TP-1001) & ECE Wireless Labs" },
        { level: 11, name: "11th Floor", code: "11F", desc: "Advanced Computing Research Suites & Seminar Carrels" },
        { level: 12, name: "12th Floor", code: "12F", desc: "Sir J. C. Bose Hall & Executive Conference Center" }
      ],
      description: "Iconic 15-story computing skyscraper housing CTECH, CINTEL, NWC, DSBS, Turing Hall, and AI/ML research facilities on Sir C.V. Raman Road facing Dr. TP Ganesan Auditorium.",
      category: "Academic & Research",
      photo: "assets/prof_male.jpg"
    },
    {
      id: "bldg-tpg",
      name: "Dr. T. P. Ganesan Auditorium",
      shortName: "TP Ganesan Auditorium",
      code: "TPG",
      zone: "Auditorium Zone",
      road: "Mahakavi Bharathiyar Road",
      floorsCount: 3,
      x: 760,
      y: 165,
      width: 135,
      height: 100,
      floors: [
        { level: 0, name: "Ground Level", code: "G", desc: "Registration Foyer, VIP Green Rooms & Media Gallery" },
        { level: 1, name: "Ramp Level", code: "1F", desc: "3,000 Capacity Grand Auditorium, Mini Hall 1 & Mini Hall 2" }
      ],
      description: "One of Asia's largest convention facilities with a 3,000-seat central auditorium, twin 300-seat mini auditoriums, and open-air plaza directly adjacent to Tech Park and facing Vendhar Square.",
      category: "Convention & Auditorium",
      photo: "assets/prof_female.jpg"
    },
    {
      id: "bldg-main",
      name: "Main Academic Block (CRC)",
      shortName: "Main Block / CRC",
      code: "MB",
      zone: "Academic Zone",
      road: "Mahatma Gandhi Road",
      floorsCount: 5,
      x: 120,
      y: 530,
      width: 110,
      height: 70,
      floors: [
        { level: 0, name: "Ground Floor", code: "G", desc: "Fluid Mechanics Lab, Structural Engineering Lab, Workshop Shed" },
        { level: 1, name: "1st Floor", code: "1F", desc: "Civil Engineering Faculty Rooms (CRC-101 to 130), CAD Lab" },
        { level: 2, name: "2nd Floor", code: "2F", desc: "Aerospace Engineering HOD & Faculty Cabins (CRC-201 to 220), Wind Tunnel" },
        { level: 3, name: "3rd Floor", code: "3F", desc: "Engineering Drawing Halls, Mechatronics Systems Lab" },
        { level: 4, name: "4th Floor", code: "4F", desc: "Central Computing Facility (CCF) & Seminar Halls" }
      ],
      description: "The 5-story engineering complex in the Southwest campus near Potheri. Houses Civil Engineering, Aerospace Engineering, and Central Research Centre (CRC).",
      category: "Academic & Engineering",
      photo: "assets/prof_male.jpg"
    },
    {
      id: "bldg-med",
      name: "SRM Medical College Hospital & Research Centre",
      shortName: "SRM Hospital & Medical College",
      code: "MED",
      zone: "Medical College Zone",
      road: "GST Road Flank",
      floorsCount: 8,
      x: 750,
      y: 440,
      width: 180,
      height: 145,
      floors: [
        { level: 0, name: "Ground Floor", code: "G", desc: "24/7 Emergency Casualty, Pharmacy, Outpatient (OPD) Reception" },
        { level: 1, name: "1st Floor", code: "1F", desc: "Diagnostic Radiology, CT/MRI, Pathology Labs" }
      ],
      description: "1200-bed multi-specialty teaching hospital providing round-the-clock emergency medical care, free consultations, and pharmacies for SRM students on GST Road flank.",
      category: "Healthcare & Emergency"
    },
    {
      id: "bldg-hostels-north",
      name: "Campus Hostels Complex (Paari, Kaari, Oori, M-Block)",
      shortName: "Hostels Complex",
      code: "HSTL",
      zone: "Hostel Blocks",
      road: "Hostel Road",
      floorsCount: 10,
      x: 440,
      y: 470,
      width: 190,
      height: 155,
      floors: [
        { level: 0, name: "Ground Floor", code: "G", desc: "Warden Office, Mess Dining Halls, Gym, Common Recreation Lounge" }
      ],
      description: "The extensive student residential enclave comprising Paari, Kaari, Oori, Adhiyaman, Nelson Mandela, and M-Block towers with dining halls and amenities.",
      category: "Residential & Hostels"
    }
  ],

  // Comprehensive SRM KTR Faculty Directory imported directly from SRMIST Portal
  // Covers Leadership, CTECH, CINTEL, NWC, DSBS, Mechanical, ECE, EEE, Civil, Bio, and Aerospace
  // Includes realistic photos where available, and photo: null for clean "No Image" fallback
  teachers: [
    // --- UNIVERSITY EXECUTIVE LEADERSHIP ---
    {
      id: "t-srm-01",
      name: "Dr. C. Muthamizhchelvan",
      title: "Vice Chancellor",
      dept: "Executive Leadership",
      deptCode: "ADMIN",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 3,
      floorLabel: "3rd Floor",
      roomNumber: "UB-301",
      cabinDetails: "Vice Chancellor's Secretariat, Executive Wing",
      email: "vc@srmist.edu.in",
      phone: "+91 44 2745 2270",
      officeHours: "By Prior Official Secretariat Appointment",
      subjects: ["University Governance", "Higher Education Leadership"],
      status: "busy",
      statusNote: "In Executive Syndicate meeting",
      photo: "assets/prof_senior.jpg",
      rating: "5.0 ★"
    },
    {
      id: "t-srm-02",
      name: "Dr. S. Ponnusamy",
      title: "Registrar",
      dept: "University Administration",
      deptCode: "ADMIN",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 1,
      floorLabel: "1st Floor",
      roomNumber: "UB-101",
      cabinDetails: "Registrar's Office, Main Administrative Foyer",
      email: "registrar@srmist.edu.in",
      phone: "+91 44 2745 3901",
      officeHours: "Mon-Fri: 3:00 PM - 5:00 PM",
      subjects: ["Academic Regulations", "University Administration"],
      status: "available",
      statusNote: "In Office - Available for official administrative queries",
      photo: null, // Demonstrates No Image
      rating: "5.0 ★"
    },
    {
      id: "t-srm-03",
      name: "Dr. T. V. Gopal",
      title: "Professor & Dean of Academics",
      dept: "Academic Administration",
      deptCode: "ADMIN",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 3,
      floorLabel: "3rd Floor",
      roomNumber: "UB-302",
      cabinDetails: "Academic Dean's Secretariat, UB 3rd Floor East Wing",
      email: "dean.academics@srmist.edu.in",
      phone: "+91 44 2741 7100",
      officeHours: "Tue, Thu: 3:30 PM - 5:00 PM (Prior Appointment)",
      subjects: ["Systems Engineering", "Curriculum Development", "Higher Education Policy"],
      status: "meeting",
      statusNote: "In Academic Council meeting in UB Executive Boardroom",
      photo: "assets/prof_senior.jpg",
      rating: "5.0 ★"
    },
    {
      id: "t-srm-04",
      name: "Dr. K. Gunasekaran",
      title: "Controller of Examinations (COE)",
      dept: "Examination Cell",
      deptCode: "ADMIN",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 3,
      floorLabel: "3rd Floor",
      roomNumber: "UB-308",
      cabinDetails: "Controller of Examinations Office, Central Wing",
      email: "coe@srmist.edu.in",
      phone: "+91 44 2745 2818",
      officeHours: "Mon-Fri: 2:00 PM - 4:00 PM",
      subjects: ["Examination Governance", "Evaluation Systems"],
      status: "available",
      statusNote: "In Cabin - Examination & transcripts cell",
      photo: null, // Demonstrates No Image
      rating: "4.9 ★"
    },
    {
      id: "t-srm-05",
      name: "Dr. B. Neppolian",
      title: "Dean (Research)",
      dept: "Directorate of Research",
      deptCode: "ADMIN",
      buildingId: "bldg-bio",
      buildingName: "School of Bio-Engineering",
      floor: 3,
      floorLabel: "3rd Floor",
      roomNumber: "BIO-301",
      cabinDetails: "Dean Research Secretariat, Bio Block 3rd Floor",
      email: "dean.research@srmist.edu.in",
      phone: "+91 44 2741 7144",
      officeHours: "Tue, Fri: 11:00 AM - 1:00 PM",
      subjects: ["Nanotechnology", "Photocatalysis", "Sponsored Research"],
      status: "available",
      statusNote: "In Office - Reviewing Ph.D. proposals",
      photo: null, // Demonstrates No Image
      rating: "4.9 ★"
    },

    // --- SCHOOL OF COMPUTING (CTECH, CINTEL, NWC, DSBS) ---
    {
      id: "t-srm-06",
      name: "Dr. Revathi Venkataraman",
      title: "Professor & Chairperson",
      dept: "School of Computing",
      deptCode: "CTECH",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 8,
      floorLabel: "8th Floor",
      roomNumber: "TP-801",
      cabinDetails: "Chairperson Suite, Room 801, East Wing",
      email: "chairperson.computing@srmist.edu.in",
      phone: "+91 44 2741 7800",
      officeHours: "Mon, Wed, Fri: 11:00 AM - 1:00 PM",
      subjects: ["Computer Networks", "Mobile Computing", "Wireless Sensor Networks"],
      status: "available",
      statusNote: "In Cabin - Welcoming student research & academic consultations",
      photo: "assets/prof_female.jpg",
      rating: "4.9 ★"
    },
    {
      id: "t-srm-07",
      name: "Dr. Niranjana G.",
      title: "Professor & Head of Department (HOD)",
      dept: "Computing Technologies (CTECH)",
      deptCode: "CTECH",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 7,
      floorLabel: "7th Floor",
      roomNumber: "TP-701",
      cabinDetails: "HOD Office Suite, Tech Park 7th Floor North",
      email: "hod.ctech.ktr@srmist.edu.in",
      phone: "+91 44 2741 7830",
      officeHours: "Tue, Thu: 2:00 PM - 4:00 PM",
      subjects: ["Data Structures & Algorithms", "Cloud Architecture", "Object Oriented Design"],
      status: "available",
      statusNote: "In Cabin - Department administrative and grievance hours",
      photo: "assets/prof_female.jpg",
      rating: "4.8 ★"
    },
    {
      id: "t-srm-08",
      name: "Dr. M. Murali",
      title: "Professor & Head of Department (HOD)",
      dept: "Computational Intelligence (CINTEL)",
      deptCode: "CINTEL",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 6,
      floorLabel: "6th Floor",
      roomNumber: "TP-601",
      cabinDetails: "HOD Suite, 6th Floor North Wing",
      email: "hod.cintel.ktr.et@srmist.edu.in",
      phone: "+91 44 2741 7838",
      officeHours: "Daily: 11:30 AM - 1:00 PM",
      subjects: ["Artificial Intelligence", "Machine Learning", "Neural Networks & Deep Learning"],
      status: "available",
      statusNote: "Available for doubt clearing & capstone project approvals",
      photo: "assets/prof_male.jpg",
      rating: "4.9 ★"
    },
    {
      id: "t-srm-09",
      name: "Dr. Annapurani Panaiyappan",
      title: "Professor & Head of Department (HOD)",
      dept: "Networking and Communications (NWC)",
      deptCode: "NWC",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 9,
      floorLabel: "9th Floor",
      roomNumber: "TP-901",
      cabinDetails: "HOD Cabin #901, Near Cisco Networking Lab",
      email: "hod.nwc.ktr@srmist.edu.in",
      phone: "+91 44 2741 7850",
      officeHours: "Mon, Wed: 3:00 PM - 4:30 PM",
      subjects: ["Cybersecurity & Cryptography", "SDN Networks", "IoT Security Protocols"],
      status: "in-class",
      statusNote: "Taking lecture in Turing Hall (Returns at 4:30 PM)",
      photo: "assets/prof_female.jpg",
      rating: "4.7 ★"
    },
    {
      id: "t-srm-10",
      name: "Dr. G. Usha",
      title: "Professor & Head of Department (HOD)",
      dept: "Data Science and Business Systems (DSBS)",
      deptCode: "DSBS",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 10,
      floorLabel: "10th Floor",
      roomNumber: "TP-1001",
      cabinDetails: "HOD Cabin #1001, Near Big Data Computing Lab",
      email: "hod.dsbs.ktr@srmist.edu.in",
      phone: "+91 44 2741 7860",
      officeHours: "Tue, Thu: 11:00 AM - 12:30 PM",
      subjects: ["Data Mining", "Predictive Analytics", "Business Intelligence"],
      status: "available",
      statusNote: "In Cabin - Consulting with Ph.D. scholars",
      photo: null, // Demonstrates No Image
      rating: "4.8 ★"
    },
    {
      id: "t-srm-11",
      name: "Dr. B. Amutha",
      title: "Professor",
      dept: "Computing Technologies (CTECH)",
      deptCode: "CTECH",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 8,
      floorLabel: "8th Floor",
      roomNumber: "TP-804",
      cabinDetails: "Senior Faculty Cabin #804, Near Turing Hall Entrance",
      email: "amuthab@srmist.edu.in",
      phone: "+91 44 2741 7834",
      officeHours: "Wed, Fri: 2:00 PM - 4:00 PM",
      subjects: ["Operating Systems", "Distributed Computing", "Software Engineering"],
      status: "available",
      statusNote: "In Cabin 804 - Project reviews in progress",
      photo: "assets/prof_female.jpg",
      rating: "4.7 ★"
    },
    {
      id: "t-srm-12",
      name: "Dr. C. Malathy",
      title: "Professor",
      dept: "Computing Technologies (CTECH)",
      deptCode: "CTECH",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 7,
      floorLabel: "7th Floor",
      roomNumber: "TP-705",
      cabinDetails: "CTECH Faculty Cubicle #705, Glass Wing",
      email: "malathyc@srmist.edu.in",
      phone: "+91 44 2741 7837",
      officeHours: "Tue, Thu: 10:00 AM - 11:30 AM",
      subjects: ["Computer Graphics", "Image Processing", "Pattern Recognition"],
      status: "busy",
      statusNote: "Reviewing Capstone Final Projects",
      photo: "assets/prof_female.jpg",
      rating: "4.8 ★"
    },
    {
      id: "t-srm-13",
      name: "Dr. S. Prabakaran",
      title: "Professor",
      dept: "Computing Technologies (Data Science)",
      deptCode: "CTECH",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 10,
      floorLabel: "10th Floor",
      roomNumber: "TP-1002",
      cabinDetails: "Big Data & Analytics Research Suite #1002",
      email: "prabakars@srmist.edu.in",
      phone: "+91 44 2741 7842",
      officeHours: "Tue, Fri: 1:30 PM - 3:00 PM",
      subjects: ["Big Data Analytics", "Deep Learning Architectures", "Python for Data Science"],
      status: "available",
      statusNote: "In Research Suite TP-1002",
      photo: "assets/prof_male.jpg",
      rating: "4.8 ★"
    },
    {
      id: "t-srm-14",
      name: "Dr. E. Poovammal",
      title: "Professor",
      dept: "Computing Technologies (CTECH)",
      deptCode: "CTECH",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 7,
      floorLabel: "7th Floor",
      roomNumber: "TP-710",
      cabinDetails: "Faculty Suite #710, Tech Park West Corridor",
      email: "poovamme@srmist.edu.in",
      phone: "+91 44 2741 7832",
      officeHours: "Mon, Thu: 11:00 AM - 12:30 PM",
      subjects: ["Cloud Computing", "Design & Analysis of Algorithms", "Software Architecture"],
      status: "available",
      statusNote: "Available for student consultations",
      photo: null, // Demonstrates No Image
      rating: "4.9 ★"
    },
    {
      id: "t-srm-15",
      name: "Dr. M. Lakshmi",
      title: "Professor",
      dept: "Computing Technologies (CTECH)",
      deptCode: "CTECH",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 7,
      floorLabel: "7th Floor",
      roomNumber: "TP-712",
      cabinDetails: "Faculty Suite #712, Central Tech Park",
      email: "lakshmim@srmist.edu.in",
      phone: "+91 44 2741 7833",
      officeHours: "Tue, Thu: 2:00 PM - 3:30 PM",
      subjects: ["Database Management Systems", "NoSQL", "Data Mining"],
      status: "available",
      statusNote: "In Cabin 712",
      photo: null,
      rating: "4.7 ★"
    },
    {
      id: "t-srm-16",
      name: "Dr. R. I. Minu",
      title: "Professor",
      dept: "Computing Technologies (CTECH)",
      deptCode: "CTECH",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 8,
      floorLabel: "8th Floor",
      roomNumber: "TP-815",
      cabinDetails: "Faculty Suite #815, Near CSE Library",
      email: "minur@srmist.edu.in",
      phone: "+91 44 2741 7835",
      officeHours: "Mon, Wed: 1:30 PM - 3:00 PM",
      subjects: ["Computer Vision", "Machine Intelligence", "Autonomous Systems"],
      status: "in-class",
      statusNote: "In Turing Hall giving lecture",
      photo: "assets/prof_female.jpg",
      rating: "4.8 ★"
    },
    {
      id: "t-srm-17",
      name: "Dr. G. Vadivu",
      title: "Professor",
      dept: "Computing Technologies (CTECH)",
      deptCode: "CTECH",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 7,
      floorLabel: "7th Floor",
      roomNumber: "TP-718",
      cabinDetails: "Faculty Cabin #718",
      email: "vadivug@srmist.edu.in",
      phone: "+91 44 2741 7836",
      officeHours: "Wed, Fri: 10:00 AM - 11:30 AM",
      subjects: ["Semantic Web", "Ontology Engineering", "Information Retrieval"],
      status: "available",
      statusNote: "In Cabin - Research hour",
      photo: null,
      rating: "4.8 ★"
    },
    {
      id: "t-srm-18",
      name: "Dr. T. R. Saravanan",
      title: "Associate Professor",
      dept: "Computational Intelligence (CINTEL)",
      deptCode: "CINTEL",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 6,
      floorLabel: "6th Floor",
      roomNumber: "TP-608",
      cabinDetails: "Faculty Cabin #608, 6th Floor Central",
      email: "saravant1@srmist.edu.in",
      phone: "+91 44 2741 7841",
      officeHours: "Mon, Wed: 2:00 PM - 3:30 PM",
      subjects: ["Machine Learning", "Natural Language Processing", "Python Programming"],
      status: "available",
      statusNote: "In Cabin 608",
      photo: null,
      rating: "4.7 ★"
    },
    {
      id: "t-srm-19",
      name: "Dr. A. Murugan",
      title: "Professor",
      dept: "Computational Intelligence (CINTEL)",
      deptCode: "CINTEL",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 6,
      floorLabel: "6th Floor",
      roomNumber: "TP-612",
      cabinDetails: "Senior Faculty Suite #612, 6th Floor East",
      email: "murugana@srmist.edu.in",
      phone: "+91 44 2741 7843",
      officeHours: "Tue, Thu: 10:00 AM - 12:00 PM",
      subjects: ["Soft Computing", "Genetic Algorithms", "Reinforcement Learning"],
      status: "available",
      statusNote: "In Office",
      photo: "assets/prof_male.jpg",
      rating: "4.9 ★"
    },
    {
      id: "t-srm-20",
      name: "Dr. R. Annie Uthra",
      title: "Professor",
      dept: "Computational Intelligence (CINTEL)",
      deptCode: "CINTEL",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 6,
      floorLabel: "6th Floor",
      roomNumber: "TP-620",
      cabinDetails: "Faculty Cabin #620, CINTEL Corridor",
      email: "annieuthrar@srmist.edu.in",
      phone: "+91 44 2741 7845",
      officeHours: "Mon, Fri: 11:00 AM - 12:30 PM",
      subjects: ["Cognitive Computing", "Biometrics", "Deep Learning"],
      status: "available",
      statusNote: "In Cabin - Consulting student batches",
      photo: "assets/prof_female.jpg",
      rating: "4.8 ★"
    },
    {
      id: "t-srm-21",
      name: "Dr. Kayalvizhi S.",
      title: "Professor",
      dept: "Networking and Communications (NWC)",
      deptCode: "NWC",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 9,
      floorLabel: "9th Floor",
      roomNumber: "TP-905",
      cabinDetails: "Senior Faculty Cabin #905, East Wing",
      email: "kayalvis@srmist.edu.in",
      phone: "+91 44 2741 7852",
      officeHours: "Tue, Fri: 10:00 AM - 12:00 PM",
      subjects: ["Wireless Sensor Networks", "Routing Protocols", "Network Simulation"],
      status: "available",
      statusNote: "In Cabin - Ready for project evaluations",
      photo: "assets/prof_female.jpg",
      rating: "4.8 ★"
    },
    {
      id: "t-srm-22",
      name: "Dr. B. Muruganantham",
      title: "Associate Professor",
      dept: "Networking and Communications (NWC)",
      deptCode: "NWC",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 9,
      floorLabel: "9th Floor",
      roomNumber: "TP-910",
      cabinDetails: "Faculty Cabin #910, Near Cisco Lab",
      email: "muruganb@srmist.edu.in",
      phone: "+91 44 2741 7854",
      officeHours: "Wed, Thu: 2:00 PM - 4:00 PM",
      subjects: ["Cryptography & Network Security", "Ethical Hacking", "Wireless LANs"],
      status: "available",
      statusNote: "In Cabin 910",
      photo: null,
      rating: "4.7 ★"
    },
    {
      id: "t-srm-23",
      name: "Dr. K. S. Sendhil Kumar",
      title: "Associate Professor",
      dept: "Data Science and Business Systems (DSBS)",
      deptCode: "DSBS",
      buildingId: "bldg-tp",
      buildingName: "Tech Park (TP)",
      floor: 10,
      floorLabel: "10th Floor",
      roomNumber: "TP-1008",
      cabinDetails: "Faculty Cabin #1008, 10th Floor DSBS Wing",
      email: "sendhilk@srmist.edu.in",
      phone: "+91 44 2741 7862",
      officeHours: "Mon, Thu: 10:00 AM - 11:30 AM",
      subjects: ["Predictive Analytics", "Data Visualization", "R Programming"],
      status: "available",
      statusNote: "In Cabin - Analytics consultation",
      photo: null,
      rating: "4.7 ★"
    },

    // --- MECHANICAL & AUTOMOBILE ENGINEERING ---
    {
      id: "t-srm-24",
      name: "Dr. D. Kingsly Jeba Singh",
      title: "Professor & Dean",
      dept: "School of Mechanical Engineering",
      deptCode: "MECH",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 2,
      floorLabel: "2nd Floor",
      roomNumber: "UB-201",
      cabinDetails: "Mechanical Dean's Suite, West Wing UB",
      email: "dean.mech@srmist.edu.in",
      phone: "+91 44 2741 7777",
      officeHours: "Mon, Thu: 10:30 AM - 12:30 PM",
      subjects: ["Robotics & Automation", "Biomechanics", "Finite Element Method"],
      status: "available",
      statusNote: "In Cabin - Welcoming student consultations",
      photo: "assets/prof_senior.jpg",
      rating: "4.9 ★"
    },
    {
      id: "t-srm-25",
      name: "Dr. M. Cheralathan",
      title: "Professor & Head of Department",
      dept: "Department of Mechanical Engineering",
      deptCode: "MECH",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 2,
      floorLabel: "2nd Floor",
      roomNumber: "UB-205",
      cabinDetails: "HOD Mechanical Suite, Cabin 205",
      email: "hod.mech.ktr@srmist.edu.in",
      phone: "+91 44 2741 7780",
      officeHours: "Tue, Fri: 2:00 PM - 4:00 PM",
      subjects: ["Thermal Engineering", "Renewable Energy", "Heat Transfer"],
      status: "available",
      statusNote: "Available in HOD cabin for student queries",
      photo: null, // Demonstrates No Image
      rating: "4.7 ★"
    },
    {
      id: "t-srm-26",
      name: "Dr. Shubhabrata Datta",
      title: "Research Professor",
      dept: "School of Mechanical Engineering",
      deptCode: "MECH",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 2,
      floorLabel: "2nd Floor",
      roomNumber: "UB-212",
      cabinDetails: "Materials Science Research Lab Suite #212",
      email: "shubhabd@srmist.edu.in",
      phone: "+91 44 2741 7785",
      officeHours: "Mon, Wed: 11:00 AM - 1:00 PM",
      subjects: ["Computational Materials Science", "Metallurgy", "Alloy Design"],
      status: "available",
      statusNote: "In Research Suite UB-212",
      photo: "assets/prof_male.jpg",
      rating: "4.9 ★"
    },
    {
      id: "t-srm-27",
      name: "Dr. S. Prabhu",
      title: "Professor",
      dept: "Department of Mechanical Engineering",
      deptCode: "MECH",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 2,
      floorLabel: "2nd Floor",
      roomNumber: "UB-218",
      cabinDetails: "Advanced Machining & Manufacturing Suite",
      email: "prabhus@srmist.edu.in",
      phone: "+91 44 2741 7788",
      officeHours: "Wed, Fri: 2:00 PM - 3:30 PM",
      subjects: ["Advanced Manufacturing", "Micro-Machining", "Tribology"],
      status: "available",
      statusNote: "In Cabin 218",
      photo: null,
      rating: "4.8 ★"
    },
    {
      id: "t-srm-28",
      name: "Dr. G. Balaji",
      title: "Professor",
      dept: "Department of Mechanical Engineering",
      deptCode: "MECH",
      buildingId: "bldg-bel",
      buildingName: "Basic Engineering Lab (BEL) Block",
      floor: 1,
      floorLabel: "1st Floor",
      roomNumber: "BEL-104",
      cabinDetails: "Thermal & Fluid Sciences Suite, BEL Block",
      email: "balajig@srmist.edu.in",
      phone: "+91 44 2741 7792",
      officeHours: "Mon, Thu: 10:00 AM - 11:30 AM",
      subjects: ["Thermodynamics", "IC Engines", "CFD Simulation"],
      status: "available",
      statusNote: "In BEL Workshop Suite",
      photo: "assets/prof_male.jpg",
      rating: "4.7 ★"
    },

    // --- ELECTRONICS & COMMUNICATION ENGINEERING (ECE) ---
    {
      id: "t-srm-29",
      name: "Dr. Shanthi Prince",
      title: "Professor & Head of Department",
      dept: "Electronics & Communication Eng (ECE)",
      deptCode: "ECE",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 11,
      floorLabel: "11th Floor",
      roomNumber: "UB-1102",
      cabinDetails: "ECE Faculty Corridor, Cabin 1102-A",
      email: "hod.ece.ktr@srmist.edu.in",
      phone: "+91 44 2741 7820",
      officeHours: "Mon-Fri: 1:30 PM - 3:00 PM",
      subjects: ["Optical Communication", "VLSI Signal Processing", "Photonic Devices"],
      status: "available",
      statusNote: "Available in ECE department office",
      photo: "assets/prof_female.jpg",
      rating: "4.8 ★"
    },
    {
      id: "t-srm-30",
      name: "Dr. P. Aruna Priya",
      title: "Professor",
      dept: "Electronics & Communication Eng (ECE)",
      deptCode: "ECE",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 11,
      floorLabel: "11th Floor",
      roomNumber: "UB-1108",
      cabinDetails: "Senior Faculty Cabin #1108, Near Nanoelectronics Lab",
      email: "arunapp@srmist.edu.in",
      phone: "+91 44 2741 7824",
      officeHours: "Mon, Wed: 10:00 AM - 12:00 PM",
      subjects: ["Nanoelectronics", "Low Power VLSI", "Microstrip Antennas"],
      status: "available",
      statusNote: "In Cabin - Open for research project reviews",
      photo: null, // Demonstrates No Image
      rating: "4.8 ★"
    },
    {
      id: "t-srm-31",
      name: "Dr. V. Sarada",
      title: "Associate Professor",
      dept: "Electronics & Communication Eng (ECE)",
      deptCode: "ECE",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 11,
      floorLabel: "11th Floor",
      roomNumber: "UB-1115",
      cabinDetails: "Faculty Cabin #1115, Embedded Lab Corridor",
      email: "saradav@srmist.edu.in",
      phone: "+91 44 2741 7826",
      officeHours: "Tue, Thu: 2:00 PM - 3:30 PM",
      subjects: ["Embedded Systems", "IoT Architectures", "Microcontrollers"],
      status: "available",
      statusNote: "In Cabin 1115",
      photo: null,
      rating: "4.7 ★"
    },
    {
      id: "t-srm-32",
      name: "Dr. Sabitha Gauni",
      title: "Associate Professor",
      dept: "Electronics & Communication Eng (ECE)",
      deptCode: "ECE",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 11,
      floorLabel: "11th Floor",
      roomNumber: "UB-1120",
      cabinDetails: "Faculty Cabin #1120, ECE Wing",
      email: "sabithag@srmist.edu.in",
      phone: "+91 44 2741 7828",
      officeHours: "Wed, Fri: 11:00 AM - 12:30 PM",
      subjects: ["Digital Signal Processing", "Biomedical Signal Processing", "Wavelets"],
      status: "available",
      statusNote: "In Cabin 1120",
      photo: "assets/prof_female.jpg",
      rating: "4.8 ★"
    },

    // --- ELECTRICAL & ELECTRONICS ENGINEERING (EEE) ---
    {
      id: "t-srm-33",
      name: "Dr. K. Vijayakumar",
      title: "Professor & Head of Department",
      dept: "Electrical and Electronics Engineering (EEE)",
      deptCode: "EEE",
      buildingId: "bldg-bel",
      buildingName: "Basic Engineering Lab (BEL) Block",
      floor: 2,
      floorLabel: "2nd Floor",
      roomNumber: "BEL-201",
      cabinDetails: "HOD Office Suite, BEL 2nd Floor",
      email: "hod.eee.ktr@srmist.edu.in",
      phone: "+91 44 2741 7815",
      officeHours: "Wed, Fri: 11:00 AM - 1:00 PM",
      subjects: ["Power Systems Analysis", "Smart Grids", "High Voltage Engineering"],
      status: "available",
      statusNote: "In Cabin 201 - Consultation available",
      photo: "assets/prof_male.jpg",
      rating: "4.9 ★"
    },
    {
      id: "t-srm-34",
      name: "Dr. C. Subramani",
      title: "Associate Professor",
      dept: "Electrical and Electronics Engineering (EEE)",
      deptCode: "EEE",
      buildingId: "bldg-bel",
      buildingName: "Basic Engineering Lab (BEL) Block",
      floor: 2,
      floorLabel: "2nd Floor",
      roomNumber: "BEL-208",
      cabinDetails: "Renewable Energy Research Cabin #208",
      email: "subramac@srmist.edu.in",
      phone: "+91 44 2741 7818",
      officeHours: "Tue, Thu: 2:00 PM - 3:30 PM",
      subjects: ["Power Electronics", "Solar Energy Systems", "Electric Drives"],
      status: "available",
      statusNote: "In Cabin 208",
      photo: null,
      rating: "4.7 ★"
    },

    // --- CIVIL ENGINEERING ---
    {
      id: "t-srm-35",
      name: "Dr. K. S. Satyanarayanan",
      title: "Professor & Head of Department",
      dept: "Department of Civil Engineering",
      deptCode: "CIVIL",
      buildingId: "bldg-ub",
      buildingName: "University Building (UB)",
      floor: 1,
      floorLabel: "1st Floor",
      roomNumber: "UB-108",
      cabinDetails: "HOD Civil Office Suite, Ground/1st Floor Lobby Wing",
      email: "hod.civil.ktr@srmist.edu.in",
      phone: "+91 44 2741 7760",
      officeHours: "Mon, Thu: 2:30 PM - 4:00 PM",
      subjects: ["Structural Dynamics", "Earthquake Resistant Structures", "Concrete Tech"],
      status: "available",
      statusNote: "In Cabin - Welcoming site project meetings",
      photo: null, // Demonstrates No Image
      rating: "4.8 ★"
    },
    {
      id: "t-srm-36",
      name: "Dr. P. T. Ravichandran",
      title: "Professor",
      dept: "Department of Civil Engineering",
      deptCode: "CIVIL",
      buildingId: "bldg-main",
      buildingName: "Main Academic Block (CRC)",
      floor: 1,
      floorLabel: "1st Floor",
      roomNumber: "CRC-115",
      cabinDetails: "Geotechnical Engineering Suite #115, Main Academic Block",
      email: "ravichap@srmist.edu.in",
      phone: "+91 44 2741 7764",
      officeHours: "Tue, Fri: 11:00 AM - 12:30 PM",
      subjects: ["Geotechnical Engineering", "Soil Mechanics", "Foundation Design"],
      status: "available",
      statusNote: "In Cabin CRC-115",
      photo: "assets/prof_senior.jpg",
      rating: "4.9 ★"
    },
    {
      id: "t-srm-36b",
      name: "Dr. K. M. Parammasivam",
      title: "Professor & Head of Department",
      dept: "Department of Aerospace Engineering",
      deptCode: "AERO",
      buildingId: "bldg-main",
      buildingName: "Main Academic Block (CRC)",
      floor: 2,
      floorLabel: "2nd Floor",
      roomNumber: "CRC-204",
      cabinDetails: "HOD Aerospace Engineering Suite, 2nd Floor CRC",
      email: "hod.aero.ktr@srmist.edu.in",
      phone: "+91 44 2741 7790",
      officeHours: "Mon, Wed: 10:00 AM - 12:00 PM",
      subjects: ["Aerodynamics", "Gas Dynamics", "Propulsion & Wind Tunnel Testing"],
      status: "available",
      statusNote: "In Cabin CRC-204",
      photo: "assets/prof_male.jpg",
      rating: "4.9 ★"
    },

    // --- BIOENGINEERING & BIOTECHNOLOGY ---
    {
      id: "t-srm-37",
      name: "Dr. M. Vairamani",
      title: "Dean & Professor",
      dept: "School of Bioengineering",
      deptCode: "BIO",
      buildingId: "bldg-bio",
      buildingName: "School of Bio-Engineering",
      floor: 1,
      floorLabel: "1st Floor",
      roomNumber: "BIO-101",
      cabinDetails: "Dean's Secretariat, 1st Floor Bio Block",
      email: "dean.bioengg@srmist.edu.in",
      phone: "+91 44 2741 7810",
      officeHours: "Mon, Wed: 11:00 AM - 1:00 PM",
      subjects: ["Mass Spectrometry", "Proteomics", "Bio-Analytical Chemistry"],
      status: "available",
      statusNote: "In Office - Open for academic queries",
      photo: "assets/prof_senior.jpg",
      rating: "4.9 ★"
    },
    {
      id: "t-srm-38",
      name: "Dr. S. Sujatha",
      title: "Professor & Head of Department",
      dept: "Department of Biotechnology",
      deptCode: "BIO",
      buildingId: "bldg-bio",
      buildingName: "School of Bio-Engineering",
      floor: 2,
      floorLabel: "2nd Floor",
      roomNumber: "BIO-202",
      cabinDetails: "HOD Biotech Cabin #202",
      email: "hod.biotech.ktr@srmist.edu.in",
      phone: "+91 44 2741 7812",
      officeHours: "Tue, Thu: 10:00 AM - 11:30 AM",
      subjects: ["Immunotechnology", "Molecular Biology", "Genetic Engineering"],
      status: "available",
      statusNote: "In Cabin - Biotech student consultations",
      photo: null, // Demonstrates No Image
      rating: "4.7 ★"
    },
    {
      id: "t-srm-39",
      name: "Dr. D. V. L. Sarada",
      title: "Associate Professor",
      dept: "Department of Biotechnology",
      deptCode: "BIO",
      buildingId: "bldg-bio",
      buildingName: "School of Bio-Engineering",
      floor: 2,
      floorLabel: "2nd Floor",
      roomNumber: "BIO-208",
      cabinDetails: "Microbiology & Plant Biotech Cabin #208",
      email: "saradadvl@srmist.edu.in",
      phone: "+91 44 2741 7814",
      officeHours: "Wed, Fri: 2:00 PM - 3:30 PM",
      subjects: ["Microbial Biotechnology", "Biofuels", "Fermentation Tech"],
      status: "available",
      statusNote: "In Cabin 208",
      photo: null,
      rating: "4.7 ★"
    },

    // --- MEDICAL & HEALTH SCIENCES ---
    {
      id: "t-srm-40",
      name: "Dr. A. Sundaram",
      title: "Dean (Medical) & Senior Consultant",
      dept: "SRM Medical College Hospital",
      deptCode: "ADMIN",
      buildingId: "bldg-med",
      buildingName: "SRM Medical College Hospital & Research Centre",
      floor: 0,
      floorLabel: "Ground Floor",
      roomNumber: "MED-101",
      cabinDetails: "Dean Medical Secretariat, Hospital Ground Floor",
      email: "dean.medical@srmist.edu.in",
      phone: "+91 44 2745 4646",
      officeHours: "Daily: 9:00 AM - 12:00 PM",
      subjects: ["Clinical Medicine", "Healthcare Administration"],
      status: "available",
      statusNote: "In OPD Clinical Rounds",
      photo: "assets/prof_senior.jpg",
      rating: "5.0 ★"
    }
  ],

  // Real Campus Surroundings, Food Courts, Landmarks, and Hangouts grounded in Virtual Tour
  surroundings: [
    {
      id: "surr-java",
      name: "Java Canteen (Java Food Court)",
      category: "Food & Hangout",
      buildingRef: "bldg-tp",
      road: "Sir C.V. Raman Road",
      x: 100,
      y: 310,
      icon: "fa-solid fa-mug-hot",
      desc: "The most famous campus food hangout at SRM KTR! Known for juices, dosas, shawarmas, cold coffee, and lively student discussions between classes near Tech Park.",
      hours: "7:30 AM - 10:30 PM",
      popular: "Fresh juices, Shawarma, Maggi, Filter Coffee, Fried Rice"
    },
    {
      id: "surr-tpg",
      name: "Dr. T. P. Ganesan Auditorium Plaza",
      category: "Auditorium & Events",
      buildingRef: "bldg-tpg",
      road: "Mahakavi Bharathiyar Road",
      x: 430,
      y: 390,
      icon: "fa-solid fa-masks-theater",
      desc: "Asia's premier 3,000-seat auditorium hosting convocation ceremonies, Milan cultural fest, international summits, and cinema screenings.",
      hours: "8:00 AM - 8:00 PM",
      popular: "Main Hall (3000 seats), Mini Hall 1 & 2, VIP Foyer"
    },
    {
      id: "surr-clock",
      name: "Central Clock Tower & Quad Lawn",
      category: "Landmark & Greenery",
      road: "Mahatma Gandhi Road",
      x: 360,
      y: 430,
      icon: "fa-solid fa-clock",
      desc: "The scenic heart of SRM KTR campus situated in front of University Building. Landscaped lawns with Clock Tower and student seating areas on Mahatma Gandhi Road.",
      hours: "Always Open",
      popular: "Photography, Quad Seating, Evening Strolls, Student Meetups"
    },
    {
      id: "surr-tp-court",
      name: "Tech Park Food Court & Nescafe",
      category: "Food & Hangout",
      buildingRef: "bldg-tp",
      road: "Sir C.V. Raman Road",
      x: 620,
      y: 220,
      icon: "fa-solid fa-burger",
      desc: "Ground floor cafeteria in Tech Park offering quick breakfast, sandwiches, and quick snacks for students heading to CS labs.",
      hours: "8:00 AM - 8:00 PM",
      popular: "Sandwiches, Cold Coffee, South Indian Combos, Pastries"
    },
    {
      id: "surr-gazebo",
      name: "Gazebo / Campus Food Street",
      category: "Food & Hangout",
      road: "Swami Vivekananda Road",
      x: 490,
      y: 280,
      icon: "fa-solid fa-utensils",
      desc: "Outdoor shaded dining kiosks offering multiple cuisines (North Indian, Chinese, waffles, ice cream, and bakery goods) near Java Canteen.",
      hours: "10:00 AM - 10:00 PM",
      popular: "Momos, Ice cream, Rolls, Pastas, Waffles"
    },
    {
      id: "surr-chola",
      name: "Chola's Statue (X-Quad Garden)",
      category: "Landmark",
      road: "Central Quad Walkway",
      x: 430,
      y: 430,
      icon: "fa-solid fa-monument",
      desc: "Historic landmark statue of the Chola Emperor situated at the center of the X-quad landscaped walkway in front of Central Library and University Building.",
      hours: "Always Open",
      popular: "Orientation Landmark, Meeting Point, Graduation Photos"
    },
    {
      id: "surr-arch-gate",
      name: "Main Arch Gate (GST Road Entrance)",
      category: "Gate & Transit",
      road: "GST Road (NH 45)",
      x: 190,
      y: 420,
      icon: "fa-solid fa-archway",
      desc: "The monumental main entrance gate of SRM IST on National Highway 45 (GST Road) welcoming all university buses, students, and visitors.",
      hours: "24/7 Security Access",
      popular: "Campus Bus Pick-up, Security Desk, Auto Stand"
    },
    {
      id: "surr-potheri",
      name: "Potheri Railway Station & Foot Overbridge",
      category: "Gate & Transit",
      road: "GST Road Skybridge",
      x: 80,
      y: 560,
      icon: "fa-solid fa-train-subway",
      desc: "Direct suburban EMU railway connectivity to Chennai Beach & Tambaram, connected to campus via the pedestrian foot overbridge across GST Road.",
      hours: "24 Hours (EMU Trains 4 AM - 12 AM)",
      popular: "Direct transit to Tambaram, Guindy & Chennai Beach"
    },
    {
      id: "surr-cub-bank",
      name: "City Union Bank (CUB Bank & ATM)",
      category: "Banking & ATM",
      buildingRef: "bldg-tp",
      road: "Sir C.V. Raman Road",
      x: 640,
      y: 250,
      icon: "fa-solid fa-building-columns",
      desc: "Full-service City Union Bank branch and 24/7 cash withdrawal ATM located at the Tech Park ground concourse.",
      hours: "Bank: 9:30 AM - 4:30 PM | ATM: 24/7",
      popular: "Fee Payments, Student Accounts, Cash Withdrawal"
    },
    {
      id: "surr-indian-bank",
      name: "Indian Bank & Post Office",
      category: "Banking & ATM",
      buildingRef: "bldg-ub",
      road: "Swami Vivekananda Road",
      x: 290,
      y: 380,
      icon: "fa-solid fa-money-bill-transfer",
      desc: "Official campus Indian Bank branch and India Post service desk inside University Building ground floor.",
      hours: "Mon-Sat: 10:00 AM - 4:00 PM",
      popular: "Postal Dispatch, DD Issuance, Bank Counter"
    },
    {
      id: "surr-library",
      name: "SRM Central Library Complex",
      category: "Academic & Study",
      buildingRef: "bldg-lib",
      road: "Swami Vivekananda Road",
      x: 435,
      y: 350,
      icon: "fa-solid fa-book-open-reader",
      desc: "Air-conditioned 4-story learning sanctuary situated adjacent to University Building with RFID self-service, 150,000+ technical volumes, and digital research archives.",
      hours: "Mon-Sat: 8:00 AM - 10:00 PM | Sun: 9:00 AM - 5:00 PM",
      popular: "Silent Study Halls, Digital IEEE/ACM Archives, Book Issue"
    },
    {
      id: "surr-hospital",
      name: "SRM Medical Hospital & 24/7 Emergency",
      category: "Healthcare & Services",
      buildingRef: "bldg-med",
      road: "GST Road Flank",
      x: 840,
      y: 520,
      icon: "fa-solid fa-hospital",
      desc: "Comprehensive multispecialty hospital providing zero-cost primary health checkups and round-the-clock emergency casualty care for SRM students.",
      hours: "24/7 Casualty & Emergency Service",
      popular: "Student Health Scheme, Pharmacy, Blood Bank, Ambulance"
    },
    {
      id: "surr-sports",
      name: "SRM Sports Complex & Oval Ground",
      category: "Sports & Recreation",
      road: "East Campus Road",
      x: 700,
      y: 80,
      icon: "fa-solid fa-volleyball",
      desc: "Olympic-standard sports facilities featuring cricket pitch, synthetic basketball courts, badminton stadium, and indoor gym located in the northeast campus.",
      hours: "6:00 AM - 8:30 PM",
      popular: "Cricket Tournaments, Floodlit Basketball, Gym Workouts"
    },
    {
      id: "surr-temple",
      name: "Campus Temple & Spiritual Centre",
      category: "Spiritual & Peace",
      road: "Mahakavi Bharathiyar Road",
      x: 270,
      y: 270,
      icon: "fa-solid fa-om",
      desc: "Serene campus temple with prayer areas, church, and mosque nearby as seen in the virtual tour spiritual zone.",
      hours: "6:00 AM - 9:00 PM",
      popular: "Peaceful Meditation, Morning Prayers"
    }
  ],

  // Navigation Graph Nodes (Outdoor campus walkways calibrated to 1000x700 map with Virtual Tour Roads)
  navGraph: {
    nodes: [
      { id: "node-potheri", name: "Potheri Railway Station Overbridge", x: 80, y: 560, type: "transit", road: "GST Skybridge" },
      { id: "node-main-arch", name: "Main Arch Entrance Gate (GST Road)", x: 190, y: 420, type: "gate", road: "GST Road (NH 45)" },
      { id: "node-main-bldg-entrance", name: "Main Academic Block Portico (CRC)", x: 175, y: 530, type: "entrance", buildingId: "bldg-main", road: "Mahatma Gandhi Road" },
      { id: "node-mech-block", name: "Mechanical Block & Workshops", x: 200, y: 450, type: "entrance", road: "Mahatma Gandhi Road" },
      { id: "node-hitech-block", name: "Hi-Tech Block Entrance", x: 90, y: 450, type: "entrance", road: "Southwest Avenue" },
      { id: "node-ub-entrance", name: "University Building (UB) Main Entrance", x: 325, y: 405, type: "entrance", buildingId: "bldg-ub", road: "Swami Vivekananda Road" },
      { id: "node-lib-entrance", name: "Central Library Grand Steps", x: 435, y: 395, type: "entrance", buildingId: "bldg-lib", road: "Swami Vivekananda Road" },
      { id: "node-central-quad", name: "Central Clock Tower Quad", x: 360, y: 430, type: "landmark", road: "Mahatma Gandhi Road" },
      { id: "node-chola-statue", name: "Chola's Statue (X-Quad)", x: 430, y: 430, type: "landmark", road: "Mahatma Gandhi Road" },
      { id: "node-bel-entrance", name: "BEL Block Entrance", x: 440, y: 285, type: "entrance", buildingId: "bldg-bel", road: "Sir C.V. Raman Road" },
      { id: "node-bio-entrance", name: "Bio-Engineering Block Entrance", x: 535, y: 190, type: "entrance", buildingId: "bldg-bio", road: "Mahakavi Bharathiyar Road" },
      { id: "node-java-canteen", name: "Java Canteen Plaza", x: 530, y: 350, type: "food", road: "Swami Vivekananda Road" },
      { id: "node-gazebo", name: "Gazebo Food Walkway", x: 490, y: 280, type: "food", road: "Swami Vivekananda Road" },
      { id: "node-tp-entrance", name: "Tech Park Main Entrance", x: 680, y: 270, type: "entrance", buildingId: "bldg-tp", road: "Sir C.V. Raman Road" },
      { id: "node-tpg-front", name: "Dr. TP Ganesan Auditorium Plaza", x: 825, y: 265, type: "plaza", buildingId: "bldg-tpg", road: "Mahakavi Bharathiyar Road" },
      { id: "node-sports-arena", name: "Sports Arena & Oval Ground Gate", x: 700, y: 80, type: "sports", road: "East Campus Road" },
      { id: "node-hostels-entrance", name: "Campus Hostels Complex Gate", x: 535, y: 480, type: "entrance", buildingId: "bldg-hostels-north", road: "Hostel Road" },
      { id: "node-med-entrance", name: "SRM Hospital Casualty Entrance", x: 750, y: 450, type: "entrance", buildingId: "bldg-med", road: "GST Flank Road" },
      { id: "node-temple", name: "Campus Temple Plaza", x: 270, y: 270, type: "spiritual", road: "Mahakavi Bharathiyar Road" }
    ],

    // Edges with realistic distances in meters and road turn instructions
    edges: [
      { from: "node-potheri", to: "node-main-arch", dist: 130, desc: "Cross the pedestrian foot skybridge over GST Road to the Main Arch Gate" },
      { from: "node-potheri", to: "node-hitech-block", dist: 110, desc: "Turn east into Southwest Engineering campus" },
      { from: "node-hitech-block", to: "node-mech-block", dist: 110, desc: "Pass High-Tech block along workshops avenue" },
      { from: "node-hitech-block", to: "node-main-bldg-entrance", dist: 100, desc: "Turn south to Main Academic Block CRC" },
      { from: "node-main-bldg-entrance", to: "node-mech-block", dist: 90, desc: "Walk north along CRC corridor to Mechanical block" },
      { from: "node-mech-block", to: "node-main-arch", dist: 120, desc: "Head northeast toward Main Gate entrance" },
      { from: "node-main-arch", to: "node-ub-entrance", dist: 140, desc: "Enter through Main Arch onto Mahatma Gandhi Road to University Building" },
      { from: "node-main-arch", to: "node-temple", dist: 170, desc: "Walk north towards Campus Temple" },
      { from: "node-temple", to: "node-ub-entrance", dist: 150, desc: "Head south towards UB Main Reception" },
      { from: "node-ub-entrance", to: "node-central-quad", dist: 60, desc: "Step down from UB portico into Clock Tower lawn" },
      { from: "node-central-quad", to: "node-chola-statue", dist: 70, desc: "Cross landscaped garden walkway to Chola Statue" },
      { from: "node-central-quad", to: "node-lib-entrance", dist: 80, desc: "Walk northeast to Central Library main entrance" },
      { from: "node-ub-entrance", to: "node-lib-entrance", dist: 110, desc: "Walk east along Swami Vivekananda Road to Central Library" },
      { from: "node-lib-entrance", to: "node-bel-entrance", dist: 110, desc: "Head north towards BEL Workshops" },
      { from: "node-lib-entrance", to: "node-chola-statue", dist: 60, desc: "Walk south towards Chola statue" },
      { from: "node-chola-statue", to: "node-java-canteen", dist: 110, desc: "Walk east towards Java Canteen" },
      { from: "node-java-canteen", to: "node-lib-entrance", dist: 100, desc: "Head northwest towards Central Library" },
      { from: "node-bel-entrance", to: "node-bio-entrance", dist: 120, desc: "Walk northeast along Sir C.V. Raman Road to Bio-Engineering block" },
      { from: "node-bel-entrance", to: "node-gazebo", dist: 100, desc: "Walk east to Gazebo Food Street" },
      { from: "node-gazebo", to: "node-java-canteen", dist: 80, desc: "Walk south to Java Food Court" },
      { from: "node-gazebo", to: "node-tp-entrance", dist: 140, desc: "Walk east towards Tech Park Tower portico" },
      { from: "node-java-canteen", to: "node-tp-entrance", dist: 160, desc: "Walk east along Swami Vivekananda Road towards Tech Park" },
      { from: "node-tp-entrance", to: "node-tpg-front", dist: 145, desc: "Walk east across Vendhar Square to Dr. TP Ganesan Auditorium" },
      { from: "node-tp-entrance", to: "node-sports-arena", dist: 190, desc: "Walk north towards SRM Cricket Oval" },
      { from: "node-tpg-front", to: "node-sports-arena", dist: 200, desc: "Walk northwest from Auditorium towards Sports Complex" },
      { from: "node-chola-statue", to: "node-hostels-entrance", dist: 80, desc: "Walk south into student hostels avenue (Paari/Kaari/Oori/M-Block)" },
      { from: "node-java-canteen", to: "node-hostels-entrance", dist: 130, desc: "Walk south from Java towards Hostels Gate" },
      { from: "node-hostels-entrance", to: "node-med-entrance", dist: 160, desc: "Walk east along connecting road to SRM Medical College & Hospital" },
      { from: "node-tpg-front", to: "node-med-entrance", dist: 190, desc: "Walk south from Auditorium towards Medical College Hospital" }
    ]
  },

  // Indoor floor guides for SRM KTR high-rises
  indoorNavigation: {
    "bldg-tp": {
      elevatorName: "Tech Park High-Speed Lift Bank A & B (Floors G-15)",
      hasElevator: true,
      floorGuide: {
        0: "Ground Floor: Main security turnstiles, Tech Park cafeteria, CUB ATM, and elevator lobbies A & B.",
        1: "1st Floor: Ramanujan Seminar Hall and Basic Computing Labs.",
        6: "6th Floor: Computational Intelligence (CINTEL) HOD Suite (TP-601) and faculty cabins 601-630.",
        7: "7th Floor: Computing Technologies (CTECH) HOD Suite (TP-701) and faculty consultation cubicles.",
        8: "8th Floor: School of Computing Chairperson Suite (TP-801), Turing Hall, and Senior Professor Cabins.",
        9: "9th Floor: Networking & Communications (NWC) Department (TP-901) and Cisco Lab.",
        10: "10th Floor: Data Science & Business Systems (DSBS) Dept (TP-1001) & Big Data Research Labs.",
        11: "11th Floor: Advanced Computing Research Suites & Seminar Carrels.",
        12: "12th Floor: Sir J.C. Bose International Conference Auditorium."
      }
    },
    "bldg-main": {
      elevatorName: "Main Academic Block Central Stairwells & Lifts",
      hasElevator: true,
      floorGuide: {
        0: "Ground Floor: Civil Engineering Fluid Mechanics & Structural Labs, Concrete Testing Lab, Mechanical Foundry.",
        1: "1st Floor: Department of Civil Engineering Staff Cabins (CRC-101 to 130), Survey Store, CAD/GIS Centre.",
        2: "2nd Floor: Department of Aerospace Engineering (CRC-201 to 220), Aerodynamics Wind Tunnel Lab, Aircraft Hangar.",
        3: "3rd Floor: Drawing Halls 1 & 2, Thermal Engineering Research Labs, Mechatronics Center.",
        4: "4th Floor: Central Computing Facility (CRC CCF) & Engineering Conference Hall."
      }
    },
    "bldg-ub": {
      elevatorName: "University Building Central Lift Bank (Floors G-15)",
      hasElevator: true,
      floorGuide: {
        0: "Ground Floor: Reception, university post office, Indian Bank, security operations desk.",
        1: "1st Floor: Registrar's Office, Student Admissions Cell & Civil Engineering Dept (UB-108).",
        2: "2nd Floor: School of Mechanical Engineering Dean Office (UB-201) & Faculty Corridor (UB-205 to 230).",
        3: "3rd Floor: Dean of Academics Secretariat (UB-302), Controller of Examinations (COE) & Vice Chancellor Suite.",
        11: "11th Floor: Electronics & Communication Engineering (ECE) Department (UB-1102).",
        15: "15th Floor: Dr. Venkatraman Ramakrishnan Hall (Board Room), Leadership Suites & Dr. S. Radhakrishnan Hall."
      }
    },
    "bldg-tpg": {
      elevatorName: "Auditorium Gentle Ramp & Lift",
      hasElevator: true,
      floorGuide: {
        0: "Ground Level: Registration counters, VIP Green Room & Media Gallery.",
        1: "1st Floor: 3,000 Capacity Grand Auditorium & Mini Halls 1 and 2."
      }
    },
    "bldg-bio": {
      elevatorName: "Bio Block Passenger Lift",
      hasElevator: true,
      floorGuide: {
        0: "Ground Floor: Biotechnology, Plant Tissue Culture & Fermentation Labs.",
        1: "1st Floor: Dean Bioengineering Office (BIO-101) & Genetic Eng Cabins.",
        2: "2nd Floor: Genomics Research & Bioinformatics Computational Suite (BIO-202).",
        3: "3rd Floor: Nanotechnology Labs, Cleanroom & Dean Research Office (BIO-301)."
      }
    },
    "bldg-lib": {
      elevatorName: "Library Central Elevator & Marble Stairwell",
      hasElevator: true,
      floorGuide: {
        0: "Ground Floor: Circulation Counter, RFID Kiosks & Newspaper Section.",
        1: "1st Floor: Engineering Textbooks & E-Library Terminal Suite.",
        2: "2nd Floor: Quiet Research Carrels & Archive Section."
      }
    },
    "bldg-bel": {
      elevatorName: "BEL Stairwells & Service Lift",
      hasElevator: true,
      floorGuide: {
        0: "Ground Floor: Mechanical Machine Shop, Welding, Sheet Metal, Fitting & Carpentry.",
        1: "1st Floor: Basic Electrical Labs (BEL-104), FAB Lab, Prototyping Labs 1 & 2.",
        2: "2nd Floor: Department of Electrical & Electronics Engineering (EEE) (BEL-201)."
      }
    },
    "bldg-med": {
      elevatorName: "Hospital High-Capacity Stretchers & Lifts",
      hasElevator: true,
      floorGuide: {
        0: "Ground Floor: 24/7 Casualty & Emergency, Trauma Care, Student Medical Health OPD, Pharmacy.",
        1: "1st Floor: Diagnostic Radiology, Ultrasound, CT/MRI, Clinical Pathology Laboratory.",
        2: "2nd Floor: General Medicine & Surgery Wards, Intensive Care Unit (ICU)."
      }
    },
    "bldg-hostels-north": {
      elevatorName: "Hostel Block Elevators",
      hasElevator: true,
      floorGuide: {
        0: "Ground Floor: Warden office, central dining hall, recreation room."
      }
    }
  },

  // ---------------------------------------------------------------------------
  // SRM IST KTR SHUTTLE BUS & COMMUTER TRANSPORT SYSTEM
  // Grounded in official SRMIST campus transportation, bus bays & shuttle loops
  // ---------------------------------------------------------------------------
  shuttleSystem: {
    overview: {
      title: "SRM IST KTR Campus Shuttle & Bus Timings",
      tagline: "Free internal campus electric buggies & city commuter college buses",
      transportHelpdesk: "Main Administrative Building, Ground Floor, Room UB-004",
      phone: "+91 44 2745 2270 (Ext. 7041 / 7042)",
      email: "transport@srmist.edu.in",
      hours: "07:00 AM - 08:30 PM (Mon-Sat)"
    },

    // 1. Campus Shuttle Stops (Grounded in campus road geometry)
    stops: [
      {
        id: "stop-arch-gate",
        name: "Main Arch Gate Shuttle Bay",
        shortName: "Main Arch Stop",
        nodeId: "node-main-arch",
        road: "GST Road (NH 45) / Main Entrance",
        x: 190,
        y: 420,
        badge: "Transit Hub",
        desc: "Directly opposite Potheri Railway Station foot overbridge. Primary boarding bay for internal electric shuttles & city buses.",
        shelter: true,
        seating: true,
        routesServing: ["SH-01", "SH-02", "SH-03", "City Buses"]
      },
      {
        id: "stop-ub-quad",
        name: "University Building (UB) & Clock Tower Stop",
        shortName: "UB / Clock Tower",
        nodeId: "node-ub-entrance",
        road: "Swami Vivekananda Road",
        x: 325,
        y: 405,
        badge: "Admin & Civil/Mech",
        desc: "Located opposite Clock Tower Quad; serves VC Secretariat, Registrar Office, Admissions, Civil and Mechanical Eng.",
        shelter: true,
        seating: true,
        routesServing: ["SH-01", "SH-03"]
      },
      {
        id: "stop-lib-bel",
        name: "Central Library & BEL Workshops Stop",
        shortName: "Library / BEL Stop",
        nodeId: "node-lib-entrance",
        road: "Swami Vivekananda Road",
        x: 435,
        y: 395,
        badge: "Library & EEE",
        desc: "Serves SRM Central Library, First-Year BEL Engineering Labs, and Chola's Statue landscaped garden walkway.",
        shelter: true,
        seating: true,
        routesServing: ["SH-01"]
      },
      {
        id: "stop-tech-park",
        name: "Tech Park (TP) Bus Bay",
        shortName: "Tech Park Stop",
        nodeId: "node-tp-entrance",
        road: "Sir C.V. Raman Road",
        x: 680,
        y: 270,
        badge: "Computing & IT",
        desc: "High-traffic stop right at the portico of 15-story Tech Park Tower and Java Food Court.",
        shelter: true,
        seating: true,
        routesServing: ["SH-01", "SH-02", "City Buses"]
      },
      {
        id: "stop-tpg-auditorium",
        name: "Dr. TP Ganesan Auditorium Plaza Stop",
        shortName: "Auditorium Stop",
        nodeId: "node-tpg-front",
        road: "Mahakavi Bharathiyar Road",
        x: 825,
        y: 265,
        badge: "Events & Bioeng",
        desc: "Plaza stop for grand 3,000-seat auditorium convocations, Bio-Engineering block, and Sports Oval grounds.",
        shelter: true,
        seating: false,
        routesServing: ["SH-01"]
      },
      {
        id: "stop-north-hostels",
        name: "North Hostels Shuttle Depot",
        shortName: "Hostels Depot",
        nodeId: "node-hostels-entrance",
        road: "Hostel Road",
        x: 535,
        y: 480,
        badge: "Hostels Hub",
        desc: "Boarding terminus for Paari, Kaari, Oori, Adhiyaman, and M-Block resident students.",
        shelter: true,
        seating: true,
        routesServing: ["SH-01", "SH-02"]
      },
      {
        id: "stop-hospital-casualty",
        name: "SRM Medical Hospital & Casualty Stop",
        shortName: "Hospital Stop",
        nodeId: "node-med-entrance",
        road: "GST Flank Road",
        x: 750,
        y: 450,
        badge: "24/7 Medical Care",
        desc: "Direct stop in front of the 24/7 Hospital Casualty emergency entrance and Medical College.",
        shelter: true,
        seating: true,
        routesServing: ["SH-01", "SH-03"]
      }
    ],

    // 2. Internal Free Campus Shuttle Lines (Battery Electric Buggies & Shuttles)
    internalRoutes: [
      {
        id: "route-loop",
        name: "Campus Ring Line (Circular Shuttle)",
        code: "SH-01",
        badge: "Most Popular",
        type: "Free Electric Buggies & Mini-Shuttles",
        color: "#ffffff",
        fare: "FREE (Campus ID Required)",
        operatingHours: "07:00 AM – 10:30 PM Daily",
        frequencyPeak: "Every 8–10 mins (07:30–09:30 AM & 04:00–06:30 PM)",
        frequencyNormal: "Every 15 mins",
        intervalMinutes: 10,
        startHour: 7,
        endHour: 22.5,
        stopsOrder: [
          "stop-arch-gate",
          "stop-ub-quad",
          "stop-lib-bel",
          "stop-tech-park",
          "stop-tpg-auditorium",
          "stop-north-hostels",
          "stop-hospital-casualty",
          "stop-arch-gate"
        ],
        pathNodes: [
          "node-main-arch",
          "node-ub-entrance",
          "node-lib-entrance",
          "node-tp-entrance",
          "node-tpg-front",
          "node-sports-arena",
          "node-hostels-entrance",
          "node-med-entrance",
          "node-main-arch"
        ],
        description: "Clockwise circular route connecting Main Arch Gate, University Building, Central Library, Tech Park, Dr. TP Ganesan Auditorium, North Hostels, and Medical College Hospital."
      },
      {
        id: "route-hostel-express",
        name: "Hostel <-> Tech Park Express Shuttle",
        code: "SH-02 (Express)",
        badge: "High Frequency",
        type: "High-Capacity Buggies & Mini-Buses",
        color: "#d4d4d8",
        fare: "FREE (Student ID)",
        operatingHours: "07:30 AM – 09:30 AM & 04:00 PM – 06:30 PM",
        frequencyPeak: "Every 5 mins (Non-stop peak shuttle)",
        frequencyNormal: "Every 12 mins (Regular hours)",
        intervalMinutes: 6,
        startHour: 7.5,
        endHour: 18.5,
        stopsOrder: [
          "stop-north-hostels",
          "stop-tech-park",
          "stop-arch-gate"
        ],
        pathNodes: [
          "node-hostels-entrance",
          "node-java-canteen",
          "node-tp-entrance",
          "node-bel-entrance",
          "node-ub-entrance",
          "node-main-arch"
        ],
        description: "Direct fast transit created for engineering & computing students commuting between North Hostels and 15-story Tech Park Tower."
      },
      {
        id: "route-hospital",
        name: "Medical Hospital & Main Arch Connector",
        code: "SH-03 (Hospital Line)",
        badge: "24/7 Service",
        type: "Medical Clinic Van & Buggy",
        color: "#a1a1aa",
        fare: "FREE",
        operatingHours: "24 Hours (Round-the-clock)",
        frequencyPeak: "Every 12 mins",
        frequencyNormal: "Every 20 mins (Night on-call)",
        intervalMinutes: 15,
        startHour: 0,
        endHour: 24,
        stopsOrder: [
          "stop-arch-gate",
          "stop-ub-quad",
          "stop-hospital-casualty"
        ],
        pathNodes: [
          "node-main-arch",
          "node-ub-entrance",
          "node-chola-statue",
          "node-med-entrance"
        ],
        description: "Continuous transit connecting Potheri Gate, University Building, and SRM Medical College Hospital 24/7 Casualty & Outpatient entrance."
      }
    ],

    // 3. City & Suburban College Buses (Inter-City Fleets from KTR Bus Bay)
    cityRoutes: [
      {
        routeNumber: "1A",
        busNumbers: ["Bus 12", "Bus 14"],
        destination: "Tambaram (Sanatorium & West / East)",
        via: "Perungalathur, Irumbuliyur, Tambaram Sanatorium, Chromepet",
        morningArrival: "07:45 AM",
        eveningDepartures: ["04:30 PM", "05:15 PM", "06:15 PM"],
        busBay: "Bay 1 (Near Main Arch & CRC)",
        capacity: "54 Seater",
        status: "On Schedule",
        highlights: "Suburban train link, high frequency"
      },
      {
        routeNumber: "2B",
        busNumbers: ["Bus 22", "Bus 24", "Bus 28"],
        destination: "Guindy Metro & Saidapet",
        via: "Airport, Pallavaram, Meenambakkam, Little Mount, Saidapet",
        morningArrival: "07:50 AM",
        eveningDepartures: ["04:30 PM", "05:15 PM", "06:15 PM", "07:30 PM"],
        busBay: "Bay 2",
        capacity: "54 Seater AC",
        status: "On Schedule",
        highlights: "Direct Metro connectivity"
      },
      {
        routeNumber: "3",
        busNumbers: ["Bus 31", "Bus 35"],
        destination: "Koyambedu (CMBT) & Vadapalani",
        via: "Porur Tollgate, Ramapuram, Ashok Pillar, Vadapalani Metro, CMBT",
        morningArrival: "07:40 AM",
        eveningDepartures: ["04:30 PM", "05:15 PM", "06:15 PM"],
        busBay: "Bay 3",
        capacity: "54 Seater",
        status: "On Schedule",
        highlights: "Interstate bus nexus & metro link"
      },
      {
        routeNumber: "4",
        busNumbers: ["Bus 42", "Bus 46"],
        destination: "Velachery & Medavakkam (OMR Link)",
        via: "Vandalur Zoo, Camp Road, Selaiyur, Medavakkam, Vijayanagar, Velachery MRTS",
        morningArrival: "07:45 AM",
        eveningDepartures: ["04:30 PM", "05:15 PM", "06:15 PM"],
        busBay: "Bay 4",
        capacity: "54 Seater",
        status: "On Schedule",
        highlights: "OMR IT corridor connection"
      },
      {
        routeNumber: "5",
        busNumbers: ["Bus 53", "Bus 57"],
        destination: "Anna Nagar & Thirumangalam",
        via: "Maduravoyal, Mogappair, Thirumangalam Metro, Anna Nagar Roundtana",
        morningArrival: "07:40 AM",
        eveningDepartures: ["04:30 PM", "05:15 PM"],
        busBay: "Bay 5",
        capacity: "54 Seater",
        status: "On Schedule",
        highlights: "North-West Chennai corridor"
      },
      {
        routeNumber: "6",
        busNumbers: ["Bus 08", "Bus 10"],
        destination: "Chennai Central & Egmore",
        via: "Kathipara, T. Nagar, Chetpet, Egmore Station, Central Railway Terminus",
        morningArrival: "07:40 AM",
        eveningDepartures: ["04:30 PM", "05:15 PM", "06:15 PM"],
        busBay: "Bay 6",
        capacity: "54 Seater",
        status: "On Schedule",
        highlights: "Major railway junctions"
      },
      {
        routeNumber: "7",
        busNumbers: ["Bus 62", "Bus 65"],
        destination: "Chengalpattu & Maraimalai Nagar",
        via: "Singaperumal Koil, Mahindra World City, Paranur, Chengalpattu Old Bus Stand",
        morningArrival: "08:00 AM",
        eveningDepartures: ["04:35 PM", "05:20 PM", "06:30 PM"],
        busBay: "Bay 7",
        capacity: "54 Seater",
        status: "On Schedule",
        highlights: "Southbound GST Road link"
      },
      {
        routeNumber: "8",
        busNumbers: ["Bus 71", "Bus 74"],
        destination: "Avadi & Ambattur OT",
        via: "Kundrathur, Mangadu, Iyyappanthangal, Porur, Ambattur Estate, Avadi",
        morningArrival: "07:35 AM",
        eveningDepartures: ["04:30 PM", "05:15 PM"],
        busBay: "Bay 8",
        capacity: "54 Seater",
        status: "On Schedule",
        highlights: "Industrial belt & Western line"
      }
    ]
  }
};
